name: OptScanX Daily Run

on:
  schedule:
    - cron: "0 9 * * *"  # كل يوم الساعة 9 صباحًا UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python main.py
        env:
          FINNHUB_API: ${{ secrets.FINNHUB_API }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
